export default {
    SAVE_USER_AGENT: 'SAVE_USER_AGENT',   
    SURVEY_DATA_FETCH: 'SURVEY_DATA_FETCH',
    SURVEY_DATA_SUCCESS: 'SURVEY_DATA_SUCCESS',
    SURVEY_IS_LOADING: 'SURVEY_IS_LOADING',
    SURVEY_HAS_ERRORED: 'SURVEY_HAS_ERRORED',    
    ENTITY_DATA_SUCCESS: 'ENTITY_DATA_SUCCESS',
    SUBMIT_DATA_SUCCESS: 'SUBMIT_DATA_SUCCESS',
    ADD_FEEDBACK: 'ADD_FEEDBACK',
}